### PR TITLE
Added Edit Screen to pick and change image

### LINKED ISSUE #143: Feature to upload user image
Wont it be nice if the user can upload their pic in their profile ?

We need an option in the InfoScreen to upload an image, and when submitted, the image should be stored in Firebase Storage and its public URL appended to the user details in Firebase RealtimeDB.

If the user is signing-in using Social Auth, get the image link from the Account as use it as the profile pic.

### PR DESCRIPTION
**Pull request by adityathakurxd**
### Related Issue
- Fixes #143 .

### Proposed Changes
- Updated profile images to use a temporary image if null
- Added a new edit profile screen to upload the image
- Added firebase storage and image picker dependencies.

### Additional Information
- User should be redirected to a new screen to pick and upload an image that would be updated everywhere.

### Checklist
- [ ] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### Screenshots (Optional)

https://user-images.githubusercontent.com/53579386/137069532-b6935686-589e-437c-b59a-8972b67d84b0.mp4

### CODE REVIEW

**Comment by adityathakurxd** [comment]
It is still not complete tho. I am getting some issues is updating the image from Firebase storage and wanted to ask if the storage is activated on the console.

**Comment by infiniteoverflow** [comment]
> It is still not complete tho. I am getting some issues is updating the image from Firebase storage and wanted to ask if the storage is activated on the console.

yes, it is working @adityathakurxd . The uploaded pics are available in the `profilepictures` folder. I am giving you access to the console. You can just confirm that.

**Comment by adityathakurxd** [comment]
Sure! Then the only step left is to update the user data to use the uploaded image. 
I was doing something like:
`user.updateProfile(photoURL: url.toString());`  to set the profile url to download url from storage.

I don't know if it'll work 😳 Should I instead use the database to save the url?

**Comment by infiniteoverflow** [comment]
> Sure! Then the only step left is to update the user data to use the uploaded image. I was doing something like: `user.updateProfile(photoURL: url.toString());` to set the profile url to download url from storage.
> 
> I don't know if it'll work 😳 Should I instead use the database to save the url?

yeahh yeah...we need to store the URL in the DB..that way we can access it anytime we need.

**Comment by infiniteoverflow** [comment]
we are using Realtime DB , and each user is denoted by their UID , and inside the UID node ,we can have a 'imageURL' field to store the link

**Comment by adityathakurxd** [comment]
I might not be able to work on this immediately. So closing this for now.

**Pull request closed without merging**
