### PR TITLE
Added Login screen and SignUp screen using toggle button

### LINKED ISSUE #3: Login Screen and Sign up Screen
We would like to add a login and a sign up screen to be shown to users. The user should be able to toggle between the two. The illustrations that are used here is added in the assets folder.

The colors and fonts to be used is also added in the file `constants.dart` and fonts folder.

Screenshot 2021-03-03 at 11 02 27 AM

### PR DESCRIPTION
**Pull request by Neha62-lit**
closes #3

### CODE REVIEW

**Comment by Neha62-lit** [comment]
Login_Libro
SignUp_Libro

**Comment by Neha62-lit** [comment]
@infiniteoverflow Please review and merge this PR!

**Comment by infiniteoverflow** [comment]
Wow , looks good. 
I will merge this PR once the organizers let me know about the labels.

**Comment by Neha62-lit** [comment]
> Wow , looks good.
> I will merge this PR once the organizers let me know about the labels.

Okay! 👍

**Pull request merged**
