### PR TITLE
Added Login_screen SnackBar

### PR DESCRIPTION
**Pull request by rakshitkamboj**
**Changes**
1. Added a login SnackBar which display a message "Logging you In" with circularprogress indicator and automatically hides when user switches to home_screen.
2. Added a SnackBar for new user which display a message "Verify your email" when navigated to verify_email_screen.
3. If the users did not able to navigate to home_screen due to any reason then a SnackBar with "error" message will be displayed.

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@rakshitkamboj You are just running the snackbar for 7 seconds , then running the Firebase auth commands...Thats not what we should do.

Firebase sign in with email is a Future function , start the snack bar before hitting that function and once it is complete close the snackbar.

**Comment by rakshitkamboj** [comment]
@infiniteoverflow Okay So, I have to extract SnackBar from if statement and use it as soon as login button is clicked? and also hide it after completion of firebase process?

**Comment by infiniteoverflow** [comment]
> @infiniteoverflow Okay So, I have to extract SnackBar from if statement and use it as soon as login button is clicked? and also hide it after completion of firebase process?

yes

**Comment by rakshitkamboj** [comment]
@infiniteoverflow Please check it now.

**Review by infiniteoverflow — APPROVED** [review]

**Comment by infiniteoverflow** [comment]
Looks good @rakshitkamboj

**Pull request merged**
