### PR TITLE
made profile screen

### LINKED ISSUE #73: Create profile page
**Is your feature request related to a problem? Please describe.**
Right now Libro doesn't have any profile page for the user.

**Describe the solution you'd like**
I would like to make a profile page if given the design.

### PR DESCRIPTION
**Pull request by anotherwebguy**
### Related Issue
- Fixes #73  .

### Proposed Changes
made the ui of profile screen

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code

### Screenshots (Optional)
image

### CODE REVIEW

**Comment by anotherwebguy** [comment]
hope u'll merge it soon @infiniteoverflow

**Comment by anotherwebguy** [comment]
Hello sir @infiniteoverflow @Souvikns hope you will merge this pr soon :)

**Review by Souvikns — CHANGES_REQUESTED** [review]
having a single color object would be good to maintain in the future. It would be better you update the colors [here](https://github.com/infiniteoverflow/Libro/blob/main/lib/Utils/Styles.dart) then use it in your widget.

**Comment by anotherwebguy** [comment]
> having a single color object would be good to maintain in the future. It would be better you update the colors [here](https://github.com/infiniteoverflow/Libro/blob/main/lib/Utils/Styles.dart) then use it in your widget.

Sure i'll make the changes soon

**Comment by anotherwebguy** [comment]
i've made the changes u asked for sir @Souvikns .. Hope you will merge it soon @Souvikns @infiniteoverflow

**Review by Souvikns — APPROVED** [review]

**Comment by anotherwebguy** [comment]
Plz add the gssoc and level label @Souvikns @infiniteoverflow

**Comment by anotherwebguy** [comment]
Hey @Souvikns plz add the gssoc and level label as i didn't recieve the points for this pr

**Pull request merged**
