### PR TITLE
Edited for iOS devives

### PR DESCRIPTION
**Pull request by rohats871**
Edit for issue #20

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@rohats871 You have updated only the text widget. What about the container for the image that you had shared in the issue ?

And kindly mention the issue number in the top comment for reference.

**Comment by rohats871** [comment]
It works for all iOS devices , al normal and plus sizes
Screenshot 2021-03-12 at 10 12 03 PM

**Comment by infiniteoverflow** [comment]
@rohats871 I see you have used padding to center the "Continue" text , can u use the Center Widget for the same. As you can see in the second image, its totally coming below and it dosent look good right.

**Comment by rohats871** [comment]
> @rohats871 I see you have used padding to center the "Continue" text , can u use the Center Widget for the same. As you can see in the second image, its totally coming below and it dosent look good right.

Yes sir i fixed it

**Pull request merged**
