### PR TITLE
Added double back to exit on home screen

### LINKED ISSUE #76: Add Double-back Exit on Homepage
We need to override the back button and implement the "Double-back to Exit" feature. 

You can use this package : https://pub.dev/packages/double_back_to_close_app

### PR DESCRIPTION
**Pull request by D-Ajay-Kumar**
### Related Issue
- Fixes #76 

### Proposed Changes
- Double back within 2 seconds on home screen closes the app

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [x] Change In Documentation

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@D-Ajay-Kumar Can u add one more thing.

When the user first clicks on the back button , kindly show a FlutterToast saying "Press again to exit".

**Comment by D-Ajay-Kumar** [comment]
Any specific kind of style you have in mind or should I keep it standard?
WhatsApp Image 2021-03-21 at 12 30 44 PM

**Comment by infiniteoverflow** [comment]
@D-Ajay-Kumar I meant a FlutterToast , not a snackbar. 

You can use this package https://pub.dev/packages/fluttertoast

**Comment by D-Ajay-Kumar** [comment]
Could you please check the code?

**Review by infiniteoverflow — APPROVED** [review]

**Pull request merged**
