### PR TITLE
onGenerateRoute

### LINKED ISSUE #49: onGenerateRoutes Routes
## feature request related to a problem.
As the project is growing, it'll be difficult to maintain without a route system.

## Solution
Create a routes file `(onGenerateRoute)` and use routes defined in those for navigation.   

[Example](https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments#alternatively-extract-the-arguments-using-ongeneratero) of using onGenerateRoute.

Basic structure:
```
import 'package:flutter/material.dart';
Route<dynamic> generateRoute(RouteSettings settings) {
  // Here we'll handle all the routing

  switch (settings.name) {
      case 'login':
        return MaterialPageRoute(builder: (context) => LoginView())
}
```

Handle unknown routes:
```
switch (settings.name) {
  ...
  default:
    return MaterialPageRoute(builder: (context) => UndefinedView(name: settings.name,));
}
```
 Reference:
- [code snippets](https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c)

## Alternative

We can also use [auto_route](https://pub.dev/packages/auto_route/versions/1.0.0-beta.10) package.
It'll generate the routes for us, we'll just have to provide parameters. It is customizable.
`Warning`:  It's not migrated to null-safety yet.

### PR DESCRIPTION
**Pull request by nicks101**
### Related Issue
- Fixes #49 .

### Proposed Changes
- Added onGenerateRoute file containing all current routes and an error route.
- Replaced all current routes with onGenerate Named Route.

### Additional Information
- Resolved various lint erros.

### Checklist
- [ ] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@nicks101 there is a minor bug, can you fix that. This is mostly due to pushReplacement(). Can you take care of that...

The same is the case for Google and Facebook login too, but don't worry about that, I will override the back gesture on the homepage to exit the app.

https://user-images.githubusercontent.com/40236624/111077965-3da78f00-8519-11eb-81b1-a6a33668657b.mov

**Comment by infiniteoverflow** [comment]
Rest all looks wonderful. Good job !!

**Comment by nicks101** [comment]
> @nicks101 there is a minor bug, can you fix that. This is mostly due to pushReplacement(). Can you take care of that...
> 
> The same is the case for Google and Facebook login too, but don't worry about that, I will override the back gesture on the homepage to exit the app.
> 
> https://user-images.githubusercontent.com/40236624/111077965-3da78f00-8519-11eb-81b1-a6a33668657b.mov
> 
> 

Should i change all pushRreplacement to pushRreplacementandRemoveUntil ?
I'll add the removeUntil condition to null(clear all route stack).

**Comment by infiniteoverflow** [comment]
No , i guess PushNamed would be enough , it will by default work well with the pop() method. The bug was just that due to pushReplacement() used for redirecting from Login Page to any other page , a back gesture on the new screen was directly going to the Introduction screen instead of Login screen. 
So we just need to change one pushReplacement() , the one that takes the user to the email verification screen , the rest navigation happens to HomePage , where we are gonna override the back gesture with DoubleTap Exit Gesture.

**Comment by nicks101** [comment]
> No , i guess PushNamed would be enough , it will by default work well with the pop() method. The bug was just that due to pushReplacement() used for redirecting from Login Page to any other page , a back gesture on the new screen was directly going to the Introduction screen instead of Login screen. 
> So we just need to change one pushReplacement() , the one that takes the user to the email verification screen , the rest navigation happens to HomePage , where we are gonna override the back gesture with DoubleTap Exit Gesture.

Okay, will update them.

**Review by infiniteoverflow — APPROVED** [review]

**Pull request merged**
